
version: '3'
services:
  star-wars-image:
    image: 183027326420.dkr.ecr.us-east-2.amazonaws.com/star-wars-image
    ports:
    - 3000:3000
    container_name: my-app
  #####example of running mongo and mongo-expres container  and using voluems 
  # mongodb:
  #   image: mongo
  #   container_name: mongodb
  #   ports:
  #     - 27017:27017
  #   environment:
  #     - MONGO_INITDB_ROOT_USERNAME=AhmedRaef
  #     - MONGO_INITDB_ROOT_PASSWORD=AhmedRaef
  #   volumes:
  #     - mongo-data:/../../data/db
  # mongo-express:
  #   image: mongo-express
  #   container_name: mongo-express
  #   restart: always 
  #   ports:
  #     - 8080:8081
  #   environment:
  #     - ME_CONFIG_MONGODB_ADMINUSERNAME=AhmedRaef
  #     - ME_CONFIG_MONGODB_ADMINPASSWORD=AhmedRaef
  #     - ME_CONFIG_MONGODB_SERVER=mongodb
#volumes:
#  mongo-data:
#    driver: local
